# Generated by Django 5.0.6 on 2024-05-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
